In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\user\Documents\UberDataEngineering\data\uber_data.csv")
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [6]:
## Confirm the Table shape
# This will print the number of rows and columns in the DataFrame

print(df.shape)

(100000, 19)

In [8]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

In [9]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [10]:
print(df.shape)

(100000, 19)

In [11]:
df['trip_id'] = df.index + 1 # A surrogate Key

In [12]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,trip_id
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35,1
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35,2
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80,3
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62,4
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80,5

In [13]:
# Reorder columns to move 'trip_id' to the front
cols = df.columns.tolist()
cols.remove('trip_id')
df = df[['trip_id'] + cols]

In [14]:
df.head()

,trip_id,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,2,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,3,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,5,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [16]:
print(df.shape)

(100000, 20)

In [17]:
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

In [18]:
## Inspect the DataFrame again to confirm changes made
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trip_id                100000 non-null  int64
 1   VendorID               100000 non-null  int64
 2   tpep_pickup_datetime   100000 non-null  datetime64[ns]
 3   tpep_dropoff_datetime  100000 non-null  datetime64[ns]
 4   passenger_count        100000 non-null  int64
 5   trip_distance          100000 non-null  float64
 6   pickup_longitude       100000 non-null  float64
 7   pickup_latitude        100000 non-null  float64
 8   RatecodeID             100000 non-null  int64
 9   store_and_fwd_flag     100000 non-null  object
 10  dropoff_longitude      100000 non-null  float64
 11  dropoff_latitude       100000 non-null  float64
 12  payment_type           100000 non-null  int64
 13  fare_amount            100000 non-null  float64
 14  extra                  100000 non-null  float64
 15  mta_tax                100000 non-null  float64
 16  tip_amount             100000 non-null  float64
 17  tolls_amount           100000 non-null  float64
 18  improvement_surcharge  100000 non-null  float64
 19  total_amount           100000 non-null  float64
dtypes: datetime64[ns](2), float64(12), int64(5), object(1)
memory usage: 15.3+ MB

In [19]:
print(df.columns)

Index(['trip_id', 'VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'pickup_longitude',
       'pickup_latitude', 'RatecodeID', 'store_and_fwd_flag',
       'dropoff_longitude', 'dropoff_latitude', 'payment_type', 'fare_amount',
       'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
       'improvement_surcharge', 'total_amount'],
      dtype='object')

In [21]:
df['trip_id'] = df['trip_id'].astype('int64')
df['trip_id'].count()

np.int64(100000)

#### Building Dimensional Model: Star Schema

In [ ]:
## Building the date_dim, vendor_dim, passenger_count_dim, ratecode_dim, payment_dim, pick_up_location_dim, dropoff_location_dim
# This will create the dimension tables for the star schema

date_dim = df[['tpep_pickup_datetime', 'tpep_dropoff_datetime']].reset_index(drop=True)
date_dim['pickup_year'] = date_dim['tpep_pickup_datetime'].dt.year  
date_dim['pickup_month'] = date_dim['tpep_pickup_datetime'].dt.month
date_dim['pickup_weekday'] = date_dim['tpep_pickup_datetime'].dt.weekday
date_dim['pickup_day'] = date_dim['tpep_pickup_datetime'].dt.day
date_dim['pickup_hour'] = date_dim['tpep_pickup_datetime'].dt.hour
date_dim['dropoff_year'] = date_dim['tpep_dropoff_datetime'].dt.year
date_dim['dropoff_month'] = date_dim['tpep_dropoff_datetime'].dt.month
date_dim['dropoff_weekday'] = date_dim['tpep_dropoff_datetime'].dt.weekday
date_dim['dropoff_day'] = date_dim['tpep_dropoff_datetime'].dt.day
date_dim['dropoff_hour'] = date_dim['tpep_dropoff_datetime'].dt.hour

date_dim['datetime_id'] = date_dim.index + 1
date_dim = date_dim[['datetime_id', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 
                     'pickup_year', 'pickup_month', 'pickup_weekday', 'pickup_day', 'pickup_hour',
                     'dropoff_year', 'dropoff_month', 'dropoff_weekday', 'dropoff_day', 'dropoff_hour']]

In [23]:
date_dim.head()

,datetime_id,tpep_pickup_datetime,tpep_dropoff_datetime,pickup_year,pickup_month,pickup_weekday,pickup_day,pickup_hour,dropoff_year,dropoff_month,dropoff_weekday,dropoff_day,dropoff_hour
0,1,2016-03-01,2016-03-01 00:07:55,2016,3,1,1,0,2016,3,1,1,0
1,2,2016-03-01,2016-03-01 00:11:06,2016,3,1,1,0,2016,3,1,1,0
2,3,2016-03-01,2016-03-01 00:31:06,2016,3,1,1,0,2016,3,1,1,0
3,4,2016-03-01,2016-03-01 00:00:00,2016,3,1,1,0,2016,3,1,1,0
4,5,2016-03-01,2016-03-01 00:00:00,2016,3,1,1,0,2016,3,1,1,0

In [24]:
print(date_dim.shape)

(100000, 13)

The date_dim can be joined in two ways on the fact table when created:
- Via trip_id to date_id, since they are both unique
- Via tpep_pickup_datetime and tpep_dropoff_datetime

In [25]:
df[['VendorID']].drop_duplicates().reset_index(drop=True)

   VendorID
0         1
1         2

In [26]:
## vendor_dim
vendor_dim = df[['VendorID']].drop_duplicates().reset_index(drop=True)
vendor_dim['vendor_id'] = vendor_dim.index + 1
vendor_dim['vendor_name'] = np.where(vendor_dim['VendorID'] == 1, 'Creative Mobile Technologies, LLC', 'VeriFone Inc.')

In [27]:
vendor_dim.head()

   VendorID  vendor_id                        vendor_name
0         1          1  Creative Mobile Technologies, LLC
1         2          2                      VeriFone Inc.

In [28]:
vendor_dim = vendor_dim[['vendor_id', 'VendorID', 'vendor_name']]
vendor_dim

   vendor_id  VendorID                        vendor_name
0          1         1  Creative Mobile Technologies, LLC
1          2         2                      VeriFone Inc.

In [29]:
df['VendorID'].value_counts()

VendorID
2    88327
1    11673
Name: count, dtype: int64

In [34]:
df.merge(vendor_dim, how='left', left_on='VendorID', right_on='vendor_id')['vendor_id'].value_counts()

vendor_id
2    88327
1    11673
Name: count, dtype: int64

In [35]:
df['passenger_count'].count()

np.int64(100000)

In [36]:
df['passenger_count'].value_counts()

passenger_count
1    65493
2    13709
5     8748
6     6077
3     4076
4     1894
0        3
Name: count, dtype: int64

In [37]:
passenger_count_dim = df[['passenger_count']].drop_duplicates().reset_index(drop=True)
passenger_count_dim['passenger_count_id'] = passenger_count_dim.index + 1
passenger_count_dim = passenger_count_dim[['passenger_count_id','passenger_count']]

In [42]:
df.merge(passenger_count_dim, how='left', on='passenger_count')['passenger_count'].value_counts()

passenger_count
1    65493
2    13709
5     8748
6     6077
3     4076
4     1894
0        3
Name: count, dtype: int64

In [43]:
rate_code_type = {
    1:"Standard rate",
    2:"JFK",
    3:"Newark",
    4:"Nassau or Westchester",
    5:"Negotiated fare",
    6:"Group ride"
}

rate_code_dim = df[['RatecodeID']].drop_duplicates().reset_index(drop=True)
rate_code_dim['ratecode_id'] = rate_code_dim.index + 1
rate_code_dim['rate_code_name'] = rate_code_dim['RatecodeID'].map(rate_code_type)
rate_code_dim = rate_code_dim[['ratecode_id','RatecodeID','rate_code_name']]

In [45]:
rate_code_dim.head()

   ratecode_id  RatecodeID         rate_code_name
0            1           1          Standard rate
1            2           3                 Newark
2            3           2                    JFK
3            4           5        Negotiated fare
4            5           4  Nassau or Westchester

In [47]:
df.merge(rate_code_dim, how='left', on='RatecodeID')['RatecodeID'].value_counts()

RatecodeID
1    97199
2     2207
5      283
3      262
4       48
6        1
Name: count, dtype: int64

In [48]:
df['payment_type'].value_counts()

payment_type
1    66548
2    33203
3      173
4       76
Name: count, dtype: int64

In [49]:
payment_type_name = {
    1:"Credit card",
    2:"Cash",
    3:"No charge",
    4:"Dispute",
    5:"Unknown",
    6:"Voided trip"
}
payment_type_dim = df[['payment_type']].drop_duplicates().reset_index(drop=True)
payment_type_dim["payment_type_id"] = payment_type_dim.index + 1
payment_type_dim['payment_type_name'] = payment_type_dim['payment_type'].map(payment_type_name)
payment_type_dim = payment_type_dim[["payment_type_id",'payment_type','payment_type_name']]

In [50]:
payment_type_dim.head()

   payment_type_id  payment_type payment_type_name
0                1             1       Credit card
1                2             2              Cash
2                3             3         No charge
3                4             4           Dispute

In [51]:
df.merge(payment_type_dim, how='left', on='payment_type')['payment_type'].value_counts()

payment_type
1    66548
2    33203
3      173
4       76
Name: count, dtype: int64

In [58]:
pickup_location_dim = df[['pickup_longitude', 'pickup_latitude']].drop_duplicates().reset_index(drop=True)
pickup_location_dim['pickup_location_id'] = pickup_location_dim.index + 1
pickup_location_dim = pickup_location_dim[['pickup_location_id','pickup_latitude','pickup_longitude']] 


dropoff_location_dim = df[['dropoff_longitude', 'dropoff_latitude']].drop_duplicates().reset_index(drop=True)
dropoff_location_dim['dropoff_location_id'] = dropoff_location_dim.index + 1
dropoff_location_dim = dropoff_location_dim[['dropoff_location_id','dropoff_latitude','dropoff_longitude']]

In [60]:
## Now let's build the fact table

fact_table = df.merge(date_dim, how='left', left_on='trip_id', right_on='datetime_id')\
               .merge(vendor_dim, how='left', on='VendorID')\
               .merge(passenger_count_dim, how='left', on='passenger_count')\
               .merge(rate_code_dim, how='left', on='RatecodeID')\
               .merge(payment_type_dim, how='left', on='payment_type')\
              .merge(pickup_location_dim, on=['pickup_longitude', 'pickup_latitude'], how='left')\
              .merge(dropoff_location_dim, on=['dropoff_longitude', 'dropoff_latitude'], how='left')
                
fact_table.head()

,trip_id,VendorID,tpep_pickup_datetime_x,tpep_dropoff_datetime_x,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,...,dropoff_hour,vendor_id,vendor_name,passenger_count_id,ratecode_id,rate_code_name,payment_type_id,payment_type_name,pickup_location_id,dropoff_location_id
0,1,1,2016-03-01,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,...,0,1,"Creative Mobile Technologies, LLC",1,1,Standard rate,1,Credit card,1,1
1,2,1,2016-03-01,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,...,0,1,"Creative Mobile Technologies, LLC",1,1,Standard rate,1,Credit card,2,2
2,3,2,2016-03-01,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,...,0,2,VeriFone Inc.,2,1,Standard rate,1,Credit card,3,3
3,4,2,2016-03-01,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,...,0,2,VeriFone Inc.,3,1,Standard rate,1,Credit card,4,4
4,5,2,2016-03-01,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,...,0,2,VeriFone Inc.,4,2,Newark,1,Credit card,5,5

In [61]:
print(fact_table.shape)

(100000, 42)

In [64]:
df.head()

,trip_id,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,1,2016-03-01,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,2,1,2016-03-01,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,3,2,2016-03-01,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,4,2,2016-03-01,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,5,2,2016-03-01,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [65]:
fact_table = fact_table[['trip_id', 'VendorID', 'datetime_id', 'passenger_count_id',
               'ratecode_id', 'payment_type_id', 'pickup_location_id', 
               'dropoff_location_id', 'store_and_fwd_flag', 'trip_distance',
               'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
               'improvement_surcharge', 'total_amount']]

In [66]:
print(fact_table.shape)

(100000, 17)

In [ ]:
import io
import pandas as pd
import requests
if 'data_loader' not in globals():
    from mage_ai.data_preparation.decorators import data_loader
if 'test' not in globals():
    from mage_ai.data_preparation.decorators import test


@data_loader
def load_data_from_api(*args, **kwargs):
    """
    Template for loading data from API
    """
    url = 'https://storage.googleapis.com/uber-data-engineering-project-taofeek/uber_data.csv'
    response = requests.get(url)

    return pd.read_csv(io.StringIO(response.text), sep=',')


@test
def test_output(output, *args) -> None:
    """
    Template code for testing the output of the block.
    """
    assert output is not None, 'The output is undefined'

In [ ]:
import pandas as pd 
import numpy as np

if 'transformer' not in globals():
    from mage_ai.data_preparation.decorators import transformer
if 'test' not in globals():
    from mage_ai.data_preparation.decorators import test
  
@transformer
def transform(df: pd.DataFrame, *args, **kwargs):
    """
    Template code for a transformer block.

    Add more parameters to this function if this block has multiple parent blocks.
    There should be one parameter for each output variable from each parent block.

    Args:
        data: The output from the upstream parent block
        args: The output from any additional upstream blocks (if applicable)

    Returns:
        Anything (e.g. data frame, dictionary, array, int, str, etc.)
    """
    # Specify your transformation logic here
    df.drop_duplicates(inplace=True)
    df.reset_index(drop=True, inplace=True)
    df['trip_id'] = df.index + 1 # A surrogate Key 
    # Reorder columns to move 'trip_id' to the front
    cols = df.columns.tolist()
    cols.remove('trip_id')
    df = df[['trip_id'] + cols]
    df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
    df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])
    ## Building the date_dim, vendor_dim, passenger_count_dim, ratecode_dim, payment_dim, pick_up_location_dim, dropoff_location_dim
    # This will create the dimension tables for the star schema

    date_dim = df[['tpep_pickup_datetime', 'tpep_dropoff_datetime']].reset_index(drop=True)
    date_dim['pickup_year'] = date_dim['tpep_pickup_datetime'].dt.year  
    date_dim['pickup_month'] = date_dim['tpep_pickup_datetime'].dt.month
    date_dim['pickup_weekday'] = date_dim['tpep_pickup_datetime'].dt.weekday
    date_dim['pickup_day'] = date_dim['tpep_pickup_datetime'].dt.day
    date_dim['pickup_hour'] = date_dim['tpep_pickup_datetime'].dt.hour
    date_dim['dropoff_year'] = date_dim['tpep_dropoff_datetime'].dt.year
    date_dim['dropoff_month'] = date_dim['tpep_dropoff_datetime'].dt.month
    date_dim['dropoff_weekday'] = date_dim['tpep_dropoff_datetime'].dt.weekday
    date_dim['dropoff_day'] = date_dim['tpep_dropoff_datetime'].dt.day
    date_dim['dropoff_hour'] = date_dim['tpep_dropoff_datetime'].dt.hour

    date_dim['datetime_id'] = date_dim.index + 1
    date_dim = date_dim[['datetime_id', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 
                        'pickup_year', 'pickup_month', 'pickup_weekday', 'pickup_day', 'pickup_hour',
                        'dropoff_year', 'dropoff_month', 'dropoff_weekday', 'dropoff_day', 'dropoff_hour']]
    ## vendor_dim
    vendor_dim = df[['VendorID']].drop_duplicates().reset_index(drop=True)
    vendor_dim['vendor_id'] = vendor_dim.index + 1
    vendor_dim['vendor_name'] = np.where(vendor_dim['VendorID'] == 1, 'Creative Mobile Technologies, LLC', 'VeriFone Inc.')
    vendor_dim = vendor_dim[['vendor_id', 'VendorID', 'vendor_name']]
    passenger_count_dim = df[['passenger_count']].drop_duplicates().reset_index(drop=True)
    passenger_count_dim['passenger_count_id'] = passenger_count_dim.index + 1
    passenger_count_dim = passenger_count_dim[['passenger_count_id','passenger_count']]
    rate_code_type = {
            1:"Standard rate",
            2:"JFK",
            3:"Newark",
            4:"Nassau or Westchester",
            5:"Negotiated fare",
            6:"Group ride"
    }

    rate_code_dim = df[['RatecodeID']].drop_duplicates().reset_index(drop=True)
    rate_code_dim['ratecode_id'] = rate_code_dim.index + 1
    rate_code_dim['rate_code_name'] = rate_code_dim['RatecodeID'].map(rate_code_type)
    rate_code_dim = rate_code_dim[['ratecode_id','RatecodeID','rate_code_name']]
    payment_type_name = {
            1:"Credit card",
            2:"Cash",
            3:"No charge",
            4:"Dispute",
            5:"Unknown",
            6:"Voided trip"
    }
    payment_type_dim = df[['payment_type']].drop_duplicates().reset_index(drop=True)
    payment_type_dim["payment_type_id"] = payment_type_dim.index + 1
    payment_type_dim['payment_type_name'] = payment_type_dim['payment_type'].map(payment_type_name)
    payment_type_dim = payment_type_dim[["payment_type_id",'payment_type','payment_type_name']]

    pickup_location_dim = df[['pickup_longitude', 'pickup_latitude']].drop_duplicates().reset_index(drop=True)
    pickup_location_dim['pickup_location_id'] = pickup_location_dim.index + 1
    pickup_location_dim = pickup_location_dim[['pickup_location_id','pickup_latitude','pickup_longitude']] 


    dropoff_location_dim = df[['dropoff_longitude', 'dropoff_latitude']].drop_duplicates().reset_index(drop=True)
    dropoff_location_dim['dropoff_location_id'] = dropoff_location_dim.index + 1
    dropoff_location_dim = dropoff_location_dim[['dropoff_location_id','dropoff_latitude','dropoff_longitude']]
    ## Now let's build the fact table

    fact_table = df.merge(date_dim, how='left', left_on='trip_id', right_on='datetime_id')\
                .merge(vendor_dim, how='left', on='VendorID')\
                .merge(passenger_count_dim, how='left', on='passenger_count')\
                .merge(rate_code_dim, how='left', on='RatecodeID')\
                .merge(payment_type_dim, how='left', on='payment_type')\
                .merge(pickup_location_dim, on=['pickup_longitude', 'pickup_latitude'], how='left')\
                .merge(dropoff_location_dim, on=['dropoff_longitude', 'dropoff_latitude'], how='left')
    fact_table = fact_table[['trip_id', 'VendorID', 'datetime_id', 'passenger_count_id',
               'ratecode_id', 'payment_type_id', 'pickup_location_id', 
               'dropoff_location_id', 'store_and_fwd_flag', 'trip_distance',
               'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
               'improvement_surcharge', 'total_amount']]  
    return {"datetime_dim":date_dim.to_dict(orient="dict"),
    "passenger_count_dim":passenger_count_dim.to_dict(orient="dict"),
    "vendor_dim":vendor_dim.to_dict(orient="dict"),
    "rate_code_dim":rate_code_dim.to_dict(orient="dict"),
    "pickup_location_dim":pickup_location_dim.to_dict(orient="dict"),
    "dropoff_location_dim":dropoff_location_dim.to_dict(orient="dict"),
    "payment_type_dim":payment_type_dim.to_dict(orient="dict"),
    "fact_table":fact_table.to_dict(orient="dict")}




@test
def test_output(output, *args) -> None:
    """
    Template code for testing the output of the block.
    """
    print(type(output))
    assert output is not None, 'The output is undefined'

In [ ]:
from mage_ai.settings.repo import get_repo_path
from mage_ai.io.bigquery import BigQuery
from mage_ai.io.config import ConfigFileLoader
from pandas import DataFrame
from os import path
from typing import Dict

if 'data_exporter' not in globals():
    from mage_ai.data_preparation.decorators import data_exporter


@data_exporter
def export_data_to_big_query(data: Dict, **kwargs) -> None:
    """
    Template for exporting data to a BigQuery warehouse.
    Specify your configuration settings in 'io_config.yaml'.

    Docs: https://docs.mage.ai/design/data-loading#bigquery
    """
    table_id = 'UberDataEngineering.uber_data_engineering.fact_table'
    config_path = path.join(get_repo_path(), 'io_config.yaml')
    config_profile = 'default'

    BigQuery.with_config(ConfigFileLoader(config_path, config_profile)).export(
        DataFrame(data['fact_table']),
        table_id,
        if_exists='replace',  # Specify resolution policy if table name already exists
    )